### ISSUE TITLE
管理端后台系统获取验证码失败

### ISSUE THREAD

**Issue by AirJunda** [zchengo/mall#2]
我git clone了你的项目在本地启动前端。但是登录界面加载不出验证码。框显示failed.
F12 显示 GET http://localhost:8000/web/captcha net::ERR_CONNECTION_REFUSED

这个怎么解决呢。我是做后端的。不太懂vue。有办法在vue代码里取消验证码吗

**Comment by zchengo** [comment]
出现net::ERR_CONNECTION_REFUSED，可能原因是：服务端没正常启动

**Comment by AirJunda** [comment]
我启动后端后这个问题解决了。感谢
